site:
  version: ~

assets:
  base: ~

database:
  driver: pdo_mysql
  host: mysql
  dbname: speedvacanze
  user: root
  password: ~
  charset: utf8mb4

swiftmailer:
  host: smtp
  port: 25
  username: user
  password: pass
  encryption: ~
  auth_mode: ~

monolog:
  email.to: 'your-mail@mailserver.me'
  email.from: 'server@localhost'