site:
  version: ~

assets:
  base: ~

database:
  driver: DATABASE_DRIVER
  host: DATABASE_HOST
  dbname: DATABASE_DBNAME
  user: DATABASE_USERNAME
  password: DATABASE_PASSWORD
  charset: utf8mb4

swiftmailer:
  host: smtp
  port: MAILER_PORT
  username: MAILER_USERNAME
  password: MAILER_PASSWORD
  encryption: ~
  auth_mode: ~

monolog:
  email.to: MONOLOG_EMAIL_TO
  email.from: MONOLOG_EMAIL_FROM